const buckets=new Map<string,{count:number;reset:number}>()
const dangerous=new Set(['php','phtml','phar','cgi','pl','py','sh','bash','exe','dll','com','bat','cmd','js','mjs','cjs','jar','msi','scr','htaccess'])
const allowedMimeByExt:Record<string,string[]>= {
 pdf:['application/pdf'],png:['image/png'],jpg:['image/jpeg'],jpeg:['image/jpeg'],gif:['image/gif'],webp:['image/webp'],txt:['text/plain'],csv:['text/csv','text/plain','application/vnd.ms-excel'],doc:['application/msword'],docx:['application/vnd.openxmlformats-officedocument.wordprocessingml.document'],xls:['application/vnd.ms-excel'],xlsx:['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],zip:['application/zip','application/x-zip-compressed']
}
const envList=(name:string)=>(process.env[name]||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean)
export function checkRateLimit(request:Request){const max=Math.max(0,Number(process.env.FORMS_RATE_LIMIT_MAX||0));if(!max)return {ok:true};const windowMs=Math.max(10,Number(process.env.FORMS_RATE_LIMIT_WINDOW_SECONDS||60))*1000;const ip=(request.headers.get('x-forwarded-for')||request.headers.get('x-real-ip')||'unknown').split(',')[0].trim();const now=Date.now(),old=buckets.get(ip);if(!old||old.reset<=now){buckets.set(ip,{count:1,reset:now+windowMs});return {ok:true}}if(old.count>=max)return {ok:false,retryAfter:Math.ceil((old.reset-now)/1000)};old.count+=1;return {ok:true}}
export function safeSuccessUrl(value:any,request:Request){const raw=String(value||'').trim();if(!raw)return undefined;if(raw.startsWith('/')&&!raw.startsWith('//'))return raw;try{const u=new URL(raw),r=new URL(request.url);if(u.protocol!=='https:')return undefined;const allowed=new Set([r.hostname.toLowerCase(),...envList('FORMS_REDIRECT_ALLOW_HOSTS')]);return allowed.has(u.hostname.toLowerCase())?u.toString():undefined}catch{return undefined}}
export function isAllowedWebhook(value:any){try{const u=new URL(String(value||''));return u.protocol==='https:'&&envList('FORMS_WEBHOOK_ALLOW_HOSTS').includes(u.hostname.toLowerCase())}catch{return false}}
export function validateUpload(file:File,acceptValue:any){const name=String(file.name||'').toLowerCase(),parts=name.split('.').filter(Boolean),ext=parts.at(-1)||'';if(!ext||dangerous.has(ext)||parts.slice(0,-1).some(x=>dangerous.has(x)))return {ok:false,error:'This file type is not allowed.'};const accepted=String(acceptValue||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);if(accepted.length){const dot=`.${ext}`,mime=String(file.type||'').toLowerCase();const match=accepted.some(a=>a===dot||a===mime||(a.endsWith('/*')&&mime.startsWith(a.slice(0,-1))));if(!match)return {ok:false,error:'This file type is not accepted for this field.'}}const known=allowedMimeByExt[ext];if(known?.length&&file.type&&!known.includes(String(file.type).toLowerCase()))return {ok:false,error:'The file extension does not match its content type.'};return {ok:true}}
