import Image from 'next/image'
import type {BhxFrontendModule} from '../../types'
const safe=(v:any)=>{const raw=String(v??'').trim();return raw.startsWith('/')||raw.startsWith('#')||/^(https?:|mailto:|tel:)/i.test(raw)?raw:''}
const ProductCard=({p,showPrice=true,showHighlights=false}:{p:any;showPrice?:boolean;showHighlights?:boolean})=>{const href=safe(p?.url);return <article className="bhx-product-card">{p?.imageUrl&&<Image src={p.imageUrl} alt={String(p.title||'')} width={800} height={800}/>}<h3>{p?.title}</h3>{p?.summary&&<p>{p.summary}</p>}{showPrice&&p?.price&&<strong>{p.price}</strong>}{showHighlights&&Array.isArray(p?.highlights)&&p.highlights.length>0&&<ul>{p.highlights.map((h:string,i:number)=><li key={i}>{h}</li>)}</ul>}{href&&<p><a href={href}>View product →</a></p>}</article>}
const module:BhxFrontendModule={id:'advanced-commerce',title:'Advanced Commerce',version:'6.6.23',webSectionTypes:['products','product_hero','product_categories','product_comparison'],renderWebSection:(section:any)=>{
 const type=String(section.sectionType||'')
 if(type==='product_hero'){const p=section.commerceProductHeroV1;return p?<div className="bhx-product-hero"><ProductCard p={p} showPrice={section.commerceShowPriceV1!==false} showHighlights={section.commerceShowHighlightsV1!==false}/></div>:null}
 if(type==='product_categories'){const cats=Array.isArray(section.commerceProductCategoriesV1)?section.commerceProductCategoriesV1:[];return <div className="bhx-product-categories" style={{'--bhx-commerce-cols':Math.max(1,Math.min(6,Number(section.commerceColumnsV1||3))),'--bhx-commerce-cols-tablet':section.commerceColumnsTabletV1==null?undefined:Math.max(1,Math.min(6,Number(section.commerceColumnsTabletV1)))} as any}>{cats.map((c:string,i:number)=><div className="bhx-product-category" key={`${c}-${i}`}>{c}</div>)}</div>}
 const products=Array.isArray(section.commerceProductsV1)?section.commerceProductsV1.filter(Boolean):[]
 if(type==='product_comparison')return <div className="bhx-product-comparison" role="region" aria-label="Product comparison"><table><thead><tr><th>Feature</th>{products.map((p:any,i:number)=><th key={p._id||i}>{p.title}</th>)}</tr></thead><tbody>{section.commerceShowPriceV1!==false&&<tr><th>Price</th>{products.map((p:any,i:number)=><td key={p._id||i}>{p.price||'—'}</td>)}</tr>}{section.commerceShowHighlightsV1!==false&&<tr><th>Highlights</th>{products.map((p:any,i:number)=><td key={p._id||i}>{Array.isArray(p.highlights)?<ul>{p.highlights.map((h:string,j:number)=><li key={j}>{h}</li>)}</ul>:'—'}</td>)}</tr>}</tbody></table></div>
 return <div className="bhx-products-grid" style={{'--bhx-commerce-cols':Math.max(1,Math.min(6,Number(section.commerceColumnsV1||3))),'--bhx-commerce-cols-tablet':section.commerceColumnsTabletV1==null?undefined:Math.max(1,Math.min(6,Number(section.commerceColumnsTabletV1)))} as any}>{products.map((p:any,i:number)=><ProductCard key={p._id||i} p={p} showPrice={section.commerceShowPriceV1!==false}/>)}</div>
}}
export default module
