const clean=(v:any)=>String(v==null?'':v).replace(/[^a-z0-9_-]+/gi,'-').toLowerCase()
const color=(v:any,fallback:string)=>v?.hex?String(v.hex):fallback
const num=(v:any,fallback:number,min:number,max:number)=>Math.max(min,Math.min(max,Number.isFinite(Number(v))?Number(v):fallback))

export function contactV1Css(id:string,data:any){
  const scope=`#${id}`
  const radius=num(data.contactBoxRadiusV1,16,0,100)
  const desktopHeight=num(data.contactMapHeightDesktopV1,420,180,900)
  const mobileHeight=num(data.contactMapHeightMobileV1,320,160,700)
  const desktop=clean(data.contactLayoutV1||'contact-map')
  const desktopGrid=desktop==='stacked'?'minmax(0,1fr)':'minmax(0,1fr) minmax(0,1fr)'
  return `${scope} .bhx-contact-v1{display:grid;grid-template-columns:${desktopGrid};gap:clamp(28px,5vw,72px);align-items:stretch;min-width:0}${scope} .bhx-contact-info{min-width:0;border-radius:${radius}px;background:${color(data.contactBoxBackgroundV1,'#ffffff')};padding:clamp(22px,3vw,38px)}${scope} .bhx-contact-info .bhx-v1-section-header{margin-bottom:22px}${scope} .bhx-contact-details{display:grid;gap:10px}${scope} .bhx-contact-details p,${scope} .bhx-contact-address{margin:0;white-space:pre-line;overflow-wrap:anywhere}${scope} .bhx-contact-address{font-style:normal}${scope} .bhx-contact-details a{text-underline-offset:3px}${scope} .bhx-contact-details a:focus-visible,${scope} .bhx-contact-map-link:focus-visible{outline:2px solid var(--bhx-accent,#4f46e5);outline-offset:3px}${scope} .bhx-contact-map{position:relative;min-width:0;min-height:${desktopHeight}px;height:${desktopHeight}px;border-radius:${radius}px;overflow:hidden;border:1px solid rgba(128,128,128,.24);background:rgba(128,128,128,.06);display:grid;place-items:center}${scope} .bhx-contact-map-frame,${scope} .bhx-contact-map-image{display:block;width:100%;height:100%;border:0}${scope} .bhx-contact-map-image{object-fit:cover}${scope} .bhx-contact-map-link{display:grid;place-items:center;width:100%;height:100%;min-height:inherit;text-decoration:none;font-weight:700;padding:24px;text-align:center}${scope} .bhx-contact-map-empty{padding:24px;text-align:center;opacity:.72}${scope} .bhx-contact-layout-map-contact .bhx-contact-map{order:1}${scope} .bhx-contact-layout-map-contact .bhx-contact-info{order:2}${scope} .bhx-contact-layout-contact-map .bhx-contact-info{order:1}${scope} .bhx-contact-layout-contact-map .bhx-contact-map{order:2}${scope} .bhx-contact-layout-stacked .bhx-contact-info{order:1}${scope} .bhx-contact-layout-stacked .bhx-contact-map{order:2}@media(max-width:767px){${scope} .bhx-contact-v1{grid-template-columns:minmax(0,1fr);gap:24px}${scope} .bhx-contact-map{height:${mobileHeight}px;min-height:${mobileHeight}px}${scope} .bhx-contact-mobile-map-contact .bhx-contact-map{order:1}${scope} .bhx-contact-mobile-map-contact .bhx-contact-info{order:2}${scope} .bhx-contact-mobile-contact-map .bhx-contact-info{order:1}${scope} .bhx-contact-mobile-contact-map .bhx-contact-map{order:2}}@media(prefers-reduced-motion:reduce){${scope} .bhx-contact-v1,${scope} .bhx-contact-v1 *{scroll-behavior:auto!important;transition:none!important;animation:none!important}}`
}
