import Image from 'next/image'
import {PortableText} from '@portabletext/react'
import {stegaClean} from 'next-sanity'
import {urlFor} from '@/sanity/lib/image'
import V1SectionButton from './V1SectionButton'
import TextSliderRuntimeV1 from './TextSliderRuntimeV1'
import {textSliderV1Css} from './textSliderV1Css'

type AnyMap=Record<string,any>
const clean=(value:any)=>stegaClean(value==null?'':String(value))
const safeHref=(value:any)=>{const raw=clean(value).trim();if(!raw)return '';if(raw.startsWith('#')||raw.startsWith('/')||raw.startsWith('./')||raw.startsWith('../')||/^(https?:|mailto:|tel:)/i.test(raw))return raw;return ''}
const imageUrl=(image:any,w=1400,h=900)=>image?.asset?urlFor(image).width(w).height(h).fit('max').auto('format').url():''
const external=(value:any)=>{const raw=clean(value).trim();return /^https?:\/\//i.test(raw)?raw:''}
const blank=(value:any)=>['new','_blank','blank'].includes(clean(value).toLowerCase())
function SliderMedia({item,title}:{item:AnyMap;title:string}){const video=external(item.videoUrl);if(video){const yt=video.match(/(?:youtu\.be\/|youtube(?:-nocookie)?\.com\/(?:watch\?v=|embed\/))([^?&/]+)/i)?.[1];const vimeo=video.match(/vimeo\.com\/(\d+)/i)?.[1];if(yt)return <div className="bhx-text-slider-video"><iframe src={`https://www.youtube-nocookie.com/embed/${encodeURIComponent(yt)}`} title={title||'Slider video'} loading="lazy" allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowFullScreen/></div>;if(vimeo)return <div className="bhx-text-slider-video"><iframe src={`https://player.vimeo.com/video/${encodeURIComponent(vimeo)}`} title={title||'Slider video'} loading="lazy" allow="autoplay; fullscreen; picture-in-picture" allowFullScreen/></div>;return <div className="bhx-text-slider-video"><video controls preload="metadata" playsInline src={video} aria-label={title||'Slider video'}/></div>}const image=imageUrl(item.image);return image?<Image className="bhx-text-slider-image" src={image} alt={clean(item.title||'')} width={1400} height={900} sizes="(max-width: 768px) 100vw, 58vw" loading="lazy"/>:<div className="bhx-text-slider-media-placeholder" aria-hidden="true"/>}
function Slide({item,index,type}:{item:AnyMap;index:number;type:string}){const href=safeHref(item.url),targetBlank=blank(item.linkTarget),title=clean(item.title);return <article className={`bhx-text-slider-card is-${type}`} aria-label={title||`Slide ${index+1}`}>{type==='image'?<SliderMedia item={item} title={title}/>:null}<div className="bhx-text-slider-card-copy">{item.eyebrow?<span className="eyebrow">{item.eyebrow}</span>:null}{title?<h3>{title}</h3>:null}{item.text?<p>{item.text}</p>:null}{href&&item.linkText?<a className="text-link" href={href} target={targetBlank?'_blank':undefined} rel={targetBlank?'noopener noreferrer':undefined}>{item.linkText} →</a>:null}</div></article>}
function TextColumn({data}:{data:AnyMap}){const readMore=safeHref(data.readMoreUrl),enabled=data.sectionButtonsEnabledV1===true,count=Math.max(1,Math.min(2,Number(data.sectionButtonCountV1||1))),layout=clean(data.sectionButtonLayoutDesktopV1||'inline').toLowerCase(),mobileLayout=data.sectionButtonMobileOverrideV1===true?clean(data.sectionButtonLayoutMobileV1||'inherit').toLowerCase():'inherit',gap=Math.max(0,Math.min(80,Number(data.sectionButtonGapDesktopV1||12)));return <div className="bhx-text-slider-copy bhx-v1-text"><div className="bhx-v1-section-header">{data.eyebrow?<span className="eyebrow">{data.eyebrow}</span>:null}{data.heading?<h2>{data.heading}</h2>:null}{data.paragraph?<p className="lead">{data.paragraph}</p>:null}{Array.isArray(data.richText)&&data.richText.length?<div className="rich-text"><PortableText value={data.richText}/></div>:null}{readMore&&data.readMoreLabel?<p className="bhx-text-slider-read-more"><a className="text-link" href={readMore}>{data.readMoreLabel} →</a></p>:null}</div>{enabled?<div className={`bhx-text-slider-buttons bhx-v1-pro-buttons bhx-v1-pro-buttons-${layout} bhx-v1-pro-buttons-mobile-${mobileLayout}`} style={{gap:`${gap}px`}}><V1SectionButton content={data.sectionPrimaryButtonV1} desktop={data.sectionPrimaryButtonDesktopV1} mobile={data.sectionButtonMobileOverrideV1?data.sectionPrimaryButtonMobileV1:undefined}/>{count>1?<V1SectionButton content={data.sectionSecondaryButtonV1} desktop={data.sectionSecondaryButtonDesktopV1} mobile={data.sectionButtonMobileOverrideV1?data.sectionSecondaryButtonMobileV1:undefined} kind="secondary"/>:null}</div>:null}</div>}
function legacyItems(data:AnyMap){return Array.isArray(data.items)?data.items.filter((item:any)=>item?.enabled!==false).map((item:any,index:number)=>({_key:item._key||`legacy-${index}`,eyebrow:item.eyebrow,title:item.title,text:item.text,image:item.image,videoUrl:item.videoUrl,url:item.link?.url,linkText:item.link?.label,linkTarget:item.link?.newWindow?'new':'same'})):[]}
export default function TextSliderV1({data,ownerId}:{data:AnyMap;ownerId:string}){const source=Array.isArray(data.textSliderItemsV1)&&data.textSliderItemsV1.length?data.textSliderItemsV1:legacyItems(data),items=source.filter(Boolean).slice(0,50),sliderType=clean(data.textSliderTypeV1||'image').toLowerCase()==='content'?'content':'image',layout=['text-slider','slider-text','stacked'].includes(clean(data.textSliderLayoutV1))?clean(data.textSliderLayoutV1):'text-slider',visible=clean(data.columnVisibility||'both'),showText=visible!=='column2',showSlider=visible!=='column1',mobile=clean(data.mobileLayout||'desktop');return <div className={`bhx-text-slider-v1 bhx-text-slider-layout-${layout} bhx-text-slider-mobile-${mobile}`} data-bhx-text-slider-v1 data-slider-type={sliderType}><style dangerouslySetInnerHTML={{__html:textSliderV1Css(ownerId,data)}}/>{showText?<TextColumn data={data}/>:null}{showSlider?<div className="bhx-text-slider-media bhx-v1-media"><TextSliderRuntimeV1 autoplay={data.textSliderAutoplay===true} seconds={Number(data.textSliderAutoplaySeconds||5)} showArrows={data.textSliderShowArrows!==false} showDots={data.textSliderShowDots!==false} enableDrag={data.textSliderEnableDrag!==false} pauseOnHover={data.textSliderPauseOnHover!==false} label={clean(data.heading||'Text and media slider')}>{items.map((item:any,index:number)=><Slide key={item?._key||index} item={item} index={index} type={sliderType}/>)}</TextSliderRuntimeV1></div>:null}</div>}
