'use client'

import Image from 'next/image'
import {PortableText} from '@portabletext/react'
import {useEffect,useMemo,useRef,useState,type PointerEvent as ReactPointerEvent,type ReactNode} from 'react'
import {urlFor} from '@/sanity/lib/image'
import V1Icon from './V1Icon'
import V1SectionButton from './V1SectionButton'

const text=(v:any)=>String(v??'')
const imageUrl=(image:any,w=1200,h=800)=>image?.asset?urlFor(image).width(w).height(h).url():''
const safe=(v:any)=>{const raw=text(v).trim();if(!raw)return '';if(raw.startsWith('#')||raw.startsWith('/')||/^(https?:|mailto:|tel:)/i.test(raw))return raw;return ''}
const fontCss=(v:any)=>{const x=text(v);const map:Record<string,string>={'System UI':"system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif",'Arial / Helvetica':'Arial,Helvetica,sans-serif','Georgia':'Georgia,serif','Times New Roman':"'Times New Roman',Times,serif",'Courier New':"'Courier New',Courier,monospace",'Trebuchet MS':"'Trebuchet MS',Arial,sans-serif",'Verdana':'Verdana,Geneva,sans-serif'};return map[x]||'inherit'}
function Header({data}:{data:any}){if(String(data.sectionType||'')==='benefits'&&data.benefitsShowTextContentV1!==true)return null;return <div className="bhx-v1-section-header">{data.eyebrow&&<span className="eyebrow">{data.eyebrow}</span>}{data.heading&&<h2>{data.heading}</h2>}{data.paragraph&&<p className="lead">{data.paragraph}</p>}{Array.isArray(data.richText)&&data.richText.length>0&&<div className="rich-text"><PortableText value={data.richText}/></div>}</div>}
function Actions({data}:{data:any}){if(data.sectionButtonsEnabledV1!==true)return null;const count=Math.max(1,Math.min(2,Number(data.sectionButtonCountV1||1)));return <div className={`bhx-v1-pro-buttons bhx-v1-pro-buttons-${String(data.sectionButtonLayoutDesktopV1||'inline')} bhx-v1-pro-buttons-mobile-${String(data.sectionButtonLayoutMobileV1||'inherit')}`}><V1SectionButton content={data.sectionPrimaryButtonV1} desktop={data.sectionPrimaryButtonDesktopV1} mobile={data.sectionButtonMobileOverrideV1?data.sectionPrimaryButtonMobileV1:undefined}/>{count>1&&<V1SectionButton content={data.sectionSecondaryButtonV1} desktop={data.sectionSecondaryButtonDesktopV1} mobile={data.sectionButtonMobileOverrideV1?data.sectionSecondaryButtonMobileV1:undefined} kind="secondary"/>}</div>}

type SliderProps={items:any[];render:(item:any,index:number)=>ReactNode;autoplay?:boolean;seconds?:number;arrows?:boolean;dots?:boolean;drag?:boolean;pauseHover?:boolean;className?:string}
function SliderFrame({items,render,autoplay=false,seconds=5,arrows=true,dots=true,drag=true,pauseHover=true,className=''}:SliderProps){
 const [index,setIndex]=useState(0),[hover,setHover]=useState(false),start=useRef<number|null>(null),delta=useRef(0)
 const count=items.length
 const go=(n:number)=>setIndex(count?((n%count)+count)%count:0)
 useEffect(()=>{if(!autoplay||seconds<=0||count<=1||(pauseHover&&hover))return;if(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)return;const id=window.setInterval(()=>setIndex(v=>(v+1)%count),Math.max(1,seconds)*1000);return()=>window.clearInterval(id)},[autoplay,seconds,count,pauseHover,hover])
 useEffect(()=>{if(index>=count&&count)setIndex(0)},[count,index])
 const down=(e:ReactPointerEvent)=>{if(!drag)return;start.current=e.clientX;delta.current=0;(e.currentTarget as HTMLElement).setPointerCapture?.(e.pointerId)}
 const move=(e:ReactPointerEvent)=>{if(start.current==null)return;delta.current=e.clientX-start.current}
 const up=()=>{if(start.current==null)return;const d=delta.current;start.current=null;delta.current=0;if(Math.abs(d)>45)go(index+(d<0?1:-1))}
 if(!count)return <div className="bhx-v1-empty">No items added yet.</div>
 return <div className={`bhx-v1-slider ${className}`} tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowLeft'){e.preventDefault();go(index-1)}if(e.key==='ArrowRight'){e.preventDefault();go(index+1)}}} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onMouseEnter={()=>setHover(true)} onMouseLeave={()=>setHover(false)}>
   <div className="bhx-v1-slider-stage">{items.map((item,i)=><div key={item?._key||item?._id||i} className={`bhx-v1-slider-slide ${i===index?'is-active':''}`} aria-hidden={i!==index}>{render(item,i)}</div>)}</div>
   {count>1&&arrows&&<><button type="button" className="bhx-v1-slider-arrow bhx-v1-slider-prev" aria-label="Previous item" onClick={()=>go(index-1)}>‹</button><button type="button" className="bhx-v1-slider-arrow bhx-v1-slider-next" aria-label="Next item" onClick={()=>go(index+1)}>›</button></>}
   {count>1&&dots&&<div className="bhx-v1-slider-dots" role="tablist" aria-label="Slider navigation">{items.map((_,i)=><button type="button" key={i} className={i===index?'is-active':''} aria-label={`Go to item ${i+1}`} aria-selected={i===index} role="tab" onClick={()=>go(i)}/>)}</div>}
 </div>
}

function BenefitCard({item,data}:{item:any;data:any}){
 const href=safe(item.url)
 const mediaType=String(item.mediaType||((item.image?.asset)?'image':'icon'))
 const hideDesktop=data.benefitsHideIconsDesktopV1===true,hideMobile=data.benefitsHideIconsMobileV1===true
 const content=<>
   <div className={`bhx-benefit-media bhx-benefit-media-${mediaType} bhx-benefit-image-${String(data.benefitsImageShapeV1||'round')} bhx-benefit-icon-${String(data.benefitsIconStyleV1||'icon_only')} ${hideDesktop?'hide-desktop':''} ${hideMobile?'hide-mobile':''}`}>
     {mediaType==='image'&&item.image?.asset?<Image src={imageUrl(item.image,480,480)} alt={text(item.title)} width={480} height={480}/>:<V1Icon name={item.icon||'outline-check-circle'} size={Number(data.benefitsIconSizeDesktopV1||50)}/>} 
   </div>
   <div className="bhx-benefit-copy">{item.title&&<h3>{item.title}</h3>}{item.text&&<p>{item.text}</p>}{item.linkText&&<span className="text-link">{item.linkText} →</span>}</div>
 </>
 return href?<a className="bhx-benefit-card" href={href} target={item.linkTarget==='new'?'_blank':undefined} rel={item.linkTarget==='new'?'noopener noreferrer':undefined}>{content}</a>:<article className="bhx-benefit-card">{content}</article>
}
function Benefits({data}:{data:any}){
 const legacy=Array.isArray(data.items)?data.items.filter((x:any)=>x?.enabled!==false).map((x:any)=>({icon:x.iconText,title:x.title,text:x.text,image:x.image,url:x.link?.url,linkText:x.link?.label,linkTarget:x.link?.newWindow?'new':'same'})):[]
 const items=Array.isArray(data.benefitsItemsV1)&&data.benefitsItemsV1.length?data.benefitsItemsV1:legacy
 const marquee=data.benefitsMarqueeEnableV1===true,step=String(data.benefitsScrollTypeV1||'continuous')==='step'
 const viewport=useRef<HTMLDivElement|null>(null),[pause,setPause]=useState(false),[stepIndex,setStepIndex]=useState(0)
 const itemWidth=Math.max(120,Number(data.benefitsMarqueeItemWidthV1||250)),gap=Math.max(0,Number(data.benefitsItemGapDesktopV1||40))
 const move=(dir:number)=>{const el=viewport.current;if(!el)return;const amount=itemWidth+gap;let next=el.scrollLeft+dir*amount;if(marquee&&!step&&el.scrollWidth>0){const half=el.scrollWidth/2;if(next<0)next+=half;if(next>=half)next-=half}el.scrollTo({left:next,behavior:'smooth'});if(step&&items.length){setStepIndex(v=>(v+dir+items.length)%items.length)}}
 useEffect(()=>{if(!marquee||!step||pause||items.length<2)return;const reduce=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;if(reduce)return;const id=window.setInterval(()=>{setStepIndex(v=>{const n=(v+1)%items.length;viewport.current?.scrollTo({left:n*(itemWidth+gap),behavior:'smooth'});return n})},Math.max(.5,Number(data.benefitsStepDelayV1||3))*1000);return()=>window.clearInterval(id)},[marquee,step,pause,items.length,data.benefitsStepDelayV1,itemWidth,gap])
 useEffect(()=>{if(!marquee||step||pause||items.length<2)return;const el=viewport.current;if(!el)return;const reduce=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;if(reduce)return;let frame=0,last=performance.now();const tick=(now:number)=>{const dt=Math.min(.05,(now-last)/1000);last=now;const half=el.scrollWidth/2;if(half>0){const raw=Math.max(1,Number(data.benefitsMarqueeSpeedV1||40));const duration=Math.max(1,.3*raw);el.scrollLeft+=half/duration*dt;if(el.scrollLeft>=half)el.scrollLeft-=half}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[marquee,step,pause,items.length,data.benefitsMarqueeSpeedV1])
 const list=marquee&&!step?[...items,...items]:items
 const style={
  '--bhx-ben-gap':`${gap}px`,'--bhx-ben-pad':`${Math.max(0,Number(data.benefitsItemPaddingDesktopV1||25))}px`,'--bhx-ben-icon-size':`${Math.max(20,Number(data.benefitsIconSizeDesktopV1||50))}px`,
  '--bhx-ben-icon-gap':`${Math.max(0,Number(data.benefitsIconGapDesktopV1||15))}px`,'--bhx-ben-rm-gap':`${Math.max(0,Number(data.benefitsReadMoreGapDesktopV1||8))}px`,'--bhx-ben-title-space':`${Math.max(0,Number(data.benefitsTitleSpacingDesktopV1||5))}px`,
  '--bhx-ben-title-size':`${Math.max(10,Number(data.benefitsTitleSizeDesktopV1||18))}px`,'--bhx-ben-text-size':`${Math.max(10,Number(data.benefitsTextSizeDesktopV1||14))}px`,
  '--bhx-ben-title-color':data.benefitsItemTitleColorV1?.hex||'#111827','--bhx-ben-text-color':data.benefitsItemTextColorV1?.hex||'#6b7280','--bhx-ben-link-color':data.benefitsItemLinkColorV1?.hex||'#4f46e5',
  '--bhx-ben-title-weight':String(data.benefitsTitleFontWeightV1||'normal'),'--bhx-ben-text-weight':String(data.benefitsTextFontWeightV1||'normal'),'--bhx-ben-title-font':fontCss(data.benefitsTitleFontFamilyV1),'--bhx-ben-text-font':fontCss(data.benefitsTextFontFamilyV1),
  '--bhx-ben-gap-tablet':String(data.benefitsTabletItemGapV1||'inherit')==='inherit'?'var(--bhx-ben-gap)':`${Number(data.benefitsTabletItemGapV1)}px`,'--bhx-ben-pad-tablet':String(data.benefitsTabletItemPaddingV1||'inherit')==='inherit'?'var(--bhx-ben-pad)':`${Number(data.benefitsTabletItemPaddingV1)}px`,'--bhx-ben-title-tablet':String(data.benefitsTabletTitleSizeV1||'inherit')==='inherit'?'var(--bhx-ben-title-size)':`${Number(data.benefitsTabletTitleSizeV1)}px`,'--bhx-ben-text-tablet':String(data.benefitsTabletTextSizeV1||'inherit')==='inherit'?'var(--bhx-ben-text-size)':`${Number(data.benefitsTabletTextSizeV1)}px`,
  '--bhx-ben-gap-mobile':`${Math.max(0,Number(data.benefitsItemGapMobileV1||30))}px`,'--bhx-ben-pad-mobile':`${Math.max(0,Number(data.benefitsItemPaddingMobileV1||25))}px`,'--bhx-ben-icon-size-mobile':`${Math.max(20,Number(data.benefitsIconSizeMobileV1||50))}px`,'--bhx-ben-icon-gap-mobile':`${Math.max(0,Number(data.benefitsIconGapMobileV1||15))}px`,'--bhx-ben-rm-gap-mobile':`${Math.max(0,Number(data.benefitsReadMoreGapMobileV1||8))}px`,'--bhx-ben-title-space-mobile':`${Math.max(0,Number(data.benefitsTitleSpacingMobileV1||5))}px`,'--bhx-ben-title-mobile':`${Math.max(10,Number(data.benefitsTitleSizeMobileV1||16))}px`,'--bhx-ben-text-mobile':`${Math.max(10,Number(data.benefitsTextSizeMobileV1||14))}px`,'--bhx-ben-item-width':`${itemWidth}px`,'--bhx-ben-icon-color':data.benefitsIconColorV1?.hex||'#4f46e5','--bhx-ben-icon-bg':data.benefitsIconBackgroundV1?.hex||'#eef2ff'
 } as any
 if(!items.length)return <><Header data={data}/><div className="bhx-v1-empty">No benefit items yet.</div><Actions data={data}/></>
 return <><Header data={data}/><div className={`bhx-benefits bhx-benefits-layout-${String(data.benefitsItemLayoutDesktopV1||'horizontal')} bhx-benefits-style-${String(data.benefitsItemStyleDesktopV1||'plain')} bhx-benefits-align-${String(data.benefitsItemAlignDesktopV1||'left')} bhx-benefits-layout-mobile-${String(data.benefitsItemLayoutMobileV1||'horizontal')} bhx-benefits-style-mobile-${String(data.benefitsItemStyleMobileV1||'plain')} bhx-benefits-align-mobile-${String(data.benefitsItemAlignMobileV1||'center')} bhx-benefits-hover-${String(data.benefitsHoverAnimationV1||'lift')} ${marquee?'is-marquee':''} ${step?'is-step':''}`} style={style} onMouseEnter={()=>data.benefitsMarqueePauseHoverV1!==false&&setPause(true)} onMouseLeave={()=>setPause(false)}>
   {marquee?<div className="bhx-benefits-carousel"><button type="button" className="bhx-benefits-nav prev" aria-label="Previous benefits" onClick={()=>move(-1)}>‹</button><div ref={viewport} className="bhx-benefits-viewport"><div className="bhx-benefits-track">{list.map((item:any,i:number)=><BenefitCard key={`${item._key||i}-${i}`} item={item} data={data}/>)}</div></div><button type="button" className="bhx-benefits-nav next" aria-label="Next benefits" onClick={()=>move(1)}>›</button>{step&&items.length>1&&<div className="bhx-v1-slider-dots">{items.map((_:any,i:number)=><button key={i} type="button" className={i===stepIndex?'is-active':''} aria-label={`Show benefit ${i+1}`} onClick={()=>{setStepIndex(i);viewport.current?.scrollTo({left:i*(itemWidth+gap),behavior:'smooth'})}}/>)}</div>}</div>:<div className="bhx-benefits-grid">{items.map((item:any,i:number)=><BenefitCard key={item._key||i} item={item} data={data}/>)}</div>}
 </div><Actions data={data}/></>
}

function Countdown({data}:{data:any}){const target=String(data.countdownTarget||'');const [now,setNow]=useState(()=>Date.now());useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(id)},[]);const end=Date.parse(target);const diff=Number.isFinite(end)?Math.max(0,end-now):0;if(!target)return <><Header data={data}/><div className="bhx-v1-empty">Countdown target not configured.</div></>;if(diff<=0)return <><Header data={data}/><div className="bhx-countdown-expired">{data.countdownExpiredTextV1||'Time is up.'}</div><Actions data={data}/></>;const sec=Math.floor(diff/1000),days=Math.floor(sec/86400),hours=Math.floor((sec%86400)/3600),mins=Math.floor((sec%3600)/60),seconds=sec%60;const units=[['Days',days,data.countdownShowDaysV1!==false],['Hours',hours,data.countdownShowHoursV1!==false],['Minutes',mins,data.countdownShowMinutesV1!==false],['Seconds',seconds,data.countdownShowSecondsV1!==false]] as const;return <><Header data={data}/><div className="bhx-countdown" role="timer" aria-live="off">{units.filter(x=>x[2]).map(([label,value])=><div key={label}><strong>{String(value).padStart(2,'0')}</strong><span>{label}</span></div>)}</div><Actions data={data}/></>}

function Tabs({data,scope}:{data:any;scope:string}){const legacy=Array.isArray(data.items)?data.items.map((x:any)=>({label:x.eyebrow||x.title,title:x.title,text:x.text,image:x.image})):[];const items=Array.isArray(data.tabsItemsV1)&&data.tabsItemsV1.length?data.tabsItemsV1:legacy;const [index,setIndex]=useState(Math.max(0,Math.min(items.length-1,Number(data.tabsDefaultIndexV1||1)-1)));const buttons=useRef<Array<HTMLButtonElement|null>>([]);useEffect(()=>{if(data.tabsAutoplayV1!==true||items.length<2)return;if(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)return;const id=window.setInterval(()=>setIndex(v=>(v+1)%items.length),Math.max(1,Number(data.tabsAutoplaySecondsV1||5))*1000);return()=>window.clearInterval(id)},[data.tabsAutoplayV1,data.tabsAutoplaySecondsV1,items.length]);if(!items.length)return <><Header data={data}/><div className="bhx-v1-empty">No tabs added yet.</div></>;const active=items[index]||items[0];return <><Header data={data}/><div className={`bhx-tabs-v1 bhx-tabs-${String(data.tabsOrientationV1||'horizontal')}`}><div role="tablist" aria-orientation={String(data.tabsOrientationV1)==='vertical'?'vertical':'horizontal'}>{items.map((x:any,i:number)=><button key={x._key||i} ref={el=>{buttons.current[i]=el}} type="button" role="tab" aria-selected={i===index} aria-controls={`${scope}-tab-panel-${i}`} tabIndex={i===index?0:-1} onClick={()=>setIndex(i)} onKeyDown={e=>{const horizontal=String(data.tabsOrientationV1||'horizontal')!=='vertical';const prev=horizontal?'ArrowLeft':'ArrowUp',next=horizontal?'ArrowRight':'ArrowDown';if(e.key===prev||e.key===next){e.preventDefault();const n=(i+(e.key===next?1:-1)+items.length)%items.length;setIndex(n);buttons.current[n]?.focus()}}}>{x.icon&&<V1Icon name={x.icon} size={18}/>}<span>{x.label||x.title||`Tab ${i+1}`}</span></button>)}</div><div role="tabpanel" id={`${scope}-tab-panel-${index}`} className="bhx-tab-panel">{active.image?.asset&&<Image src={imageUrl(active.image,1200,800)} alt={text(active.title)} width={1200} height={800}/>}<div>{active.title&&<h3>{active.title}</h3>}{active.text&&<p>{active.text}</p>}<V1SectionButton content={active.button}/></div></div></div></>}

export default function WebSectionInteractiveV1({data,type,instanceKey}:{data:any;type:string;instanceKey?:string}){const scope=String(instanceKey||data?._id||'bhx-section').replace(/[^a-zA-Z0-9_-]+/g,'-');switch(type){case'benefits':return <Benefits data={data}/>;case'countdown':return <Countdown data={data}/>;case'tabs':return <Tabs data={data} scope={scope}/>;default:return <Header data={data}/>}}
