import Image from 'next/image'
import {PortableText} from '@portabletext/react'
import {stegaClean} from 'next-sanity'
import {urlFor} from '@/sanity/lib/image'
import V1Icon from './V1Icon'
import V1SectionButton from './V1SectionButton'
import TextMediaReadMoreV1 from './TextMediaReadMoreV1'
import CodeSectionV1 from './CodeSectionV1'
import TextTextV1 from './TextTextV1'

const clean=(v:any)=>stegaClean(v==null?'':String(v))
const imageUrl=(image:any,w=1200,h=800)=>image?.asset?urlFor(image).width(w).height(h).url():''
const safeHref=(v:any)=>{const raw=clean(v).trim();if(!raw)return '';if(raw.startsWith('#')||raw.startsWith('/')||/^(https?:|mailto:|tel:)/i.test(raw))return raw;return ''}
const legacyItems=(data:any)=>Array.isArray(data.items)?data.items.filter((x:any)=>x?.enabled!==false):[]

export function SectionHeaderV1({data}:{data:any}){if(String(data.sectionType||'')==='benefits'&&data.benefitsShowTextContentV1!==true)return null;return <div className="bhx-v1-section-header">{data.eyebrow&&<span className="eyebrow">{data.eyebrow}</span>}{data.heading&&<h2>{data.heading}</h2>}{data.paragraph&&<p className="lead">{data.paragraph}</p>}{Array.isArray(data.richText)&&data.richText.length>0&&<div className="rich-text"><PortableText value={data.richText}/></div>}{data.readMoreLabel&&data.readMoreUrl&&<p><a className="text-link" href={safeHref(data.readMoreUrl)||'#'}>{data.readMoreLabel} →</a></p>}</div>}

export function SectionActions({data}:{data:any}){
 if(data.sectionButtonsEnabledV1===true){const count=Number(data.sectionButtonCountV1||1);return <div className={`bhx-v1-pro-buttons bhx-v1-pro-buttons-${String(data.sectionButtonLayoutDesktopV1||'inline')} bhx-v1-pro-buttons-mobile-${String(data.sectionButtonLayoutMobileV1||'inherit')}`} style={{gap:`${Math.max(0,Number(data.sectionButtonGapDesktopV1||12))}px`}}><V1SectionButton content={data.sectionPrimaryButtonV1} desktop={data.sectionPrimaryButtonDesktopV1} mobile={data.sectionButtonMobileOverrideV1?data.sectionPrimaryButtonMobileV1:undefined} kind="primary"/>{count>=2&&<V1SectionButton content={data.sectionSecondaryButtonV1} desktop={data.sectionSecondaryButtonDesktopV1} mobile={data.sectionButtonMobileOverrideV1?data.sectionSecondaryButtonMobileV1:undefined} kind="secondary"/>}</div>}
 const items=Array.isArray(data.buttons)?data.buttons:[]
 return items.length?<div className="bhx-v1-buttons">{items.slice(0,2).map((b:any,i:number)=>b?.label&&b?.url?<a key={i} className={`button button-${clean(b.style||'primary')}`} href={safeHref(b.url)||'#'} target={b.newWindow?'_blank':undefined} rel={b.newWindow?'noopener noreferrer':undefined}>{b.label}</a>:null)}</div>:null
}

function serviceLink(type:any,value:any){const raw=clean(value).trim();const t=clean(type||'custom');if(!raw||t==='none')return '';if(t==='email')return raw.startsWith('mailto:')?raw:`mailto:${raw}`;if(t==='tel')return raw.startsWith('tel:')?raw:`tel:${raw.replace(/[^+\d]/g,'')}`;return safeHref(raw)}
function Services({data}:{data:any}){
 const src=Array.isArray(data.servicesItemsV1)&&data.servicesItemsV1.length?data.servicesItemsV1:legacyItems(data).map((x:any)=>({...x,icon:x.iconText,url:x.link?.url,linkText:x.link?.label,linkTarget:x.link?.newWindow?'new':'same'}))
 const tabletRaw=String(data.servicesColumnsTabletModeV1||data.servicesColumnsTabletV1||'inherit');const desk=Math.max(1,Math.min(6,Number(data.servicesColumnsDesktopV1||data.itemsColumnsDesktop||3)));const tablet=tabletRaw==='inherit'?Math.max(1,Math.min(3,desk===1?1:desk>=4?3:2)):Math.max(1,Math.min(6,Number(tabletRaw||2)))
 return <><SectionHeaderV1 data={data}/><div className={`bhx-services-grid bhx-services-${String(data.servicesCardMasterLayoutV1||data.servicesCardStyleV1||'service')} bhx-hover-${String(data.servicesHoverV1Exact||data.servicesHoverV1||'lift')} bhx-last-row-${String(data.servicesLastRowAlignDesktopV1||'start')} bhx-last-row-mobile-${String(data.servicesLastRowAlignMobileV1||'start')}`} style={{'--bhx-services-cols':desk,'--bhx-services-cols-tablet':tablet,'--bhx-services-cols-mobile':Math.max(1,Math.min(4,Number(data.servicesColumnsMobileV1||data.itemsColumnsMobile||1)))} as any}>{src.map((item:any,i:number)=>{
   const href=safeHref(item.url);const visualType=String(item.visualType||((item.image?.asset)?'image':'icon'));const mode=String(item.contentMode||'image_content');const imageVisible=mode!=='content_only'&&visualType==='image'&&item.image?.asset;const iconVisible=mode!=='content_only'&&visualType==='icon'&&item.icon
   const title=item.title?(item.showTitleLink&&serviceLink('custom',item.titleUrl)?<h3><a href={serviceLink('custom',item.titleUrl)}>{item.title}</a></h3>:<h3>{item.title}</h3>):null
   const showPrice=item.showPrice===true||(item.showPrice===undefined&&data.servicesShowPriceV1!==false);const showRating=item.showRating===true||(item.showRating===undefined&&data.servicesShowRatingV1!==false)
   const buttons=Array.isArray(item.iconButtons)?item.iconButtons.filter((b:any)=>b?.enabled!==false).slice(0,Math.max(1,Math.min(3,Number(data.servicesIconButtonCountV1||3)))):[]
   const cardStyle:any={position:'relative',zIndex:Number(item.zIndex||1),transform:`translate(${Number(item.positionLeft||0)-Number(item.positionRight||0)}${item.positionUnit||'px'},${Number(item.positionTop||0)-Number(item.positionBottom||0)}${item.positionUnit||'px'})`,...(item.borderMode==='custom'?{borderStyle:item.borderType==='gradient'?'solid':String(item.borderType||'solid'),borderWidth:`${Math.max(0,Number(item.borderWidth||0))}px`,borderColor:String(item.borderColor||'#e5e7eb'),borderTopWidth:item.borderTop===false?'0':undefined,borderRightWidth:item.borderRight===false?'0':undefined,borderBottomWidth:item.borderBottom===false?'0':undefined,borderLeftWidth:item.borderLeft===false?'0':undefined,borderRadius:item.borderRadius!=null?`${Math.max(0,Number(item.borderRadius))}px`:undefined}: {})}
   const content=<>{imageVisible&&<div className={`bhx-service-visual bhx-image-shape-${String(item.imageShape||'circle')}`}><Image src={imageUrl(item.image,900,600)} alt={clean(item.title)} width={900} height={600} style={{height:`${Math.max(40,Number(item.imageHeight||320))}px`,transform:`scale(${Math.max(.25,Math.min(3,Number(item.imageScale||1)))})`}}/></div>}{iconVisible&&<div className={`bhx-v1-card-icon bhx-icon-shape-${String(item.iconShape||'circle')}`} style={{width:`${Math.max(20,Number(item.iconSize||data.servicesIconSizeDesktopV1||100))}px`,height:`${Math.max(20,Number(item.iconSize||data.servicesIconSizeDesktopV1||100))}px`,color:String(item.iconColor||'#2563eb'),background:String(item.iconBackgroundColor||'#eff6ff')}}><V1Icon name={item.icon} size={Math.max(18,Number(item.iconSize||data.servicesIconSizeDesktopV1||100)*.5)}/></div>}{mode!=='image_only'&&<div className="bhx-service-content">{item.eyebrow&&<span className="eyebrow">{item.eyebrow}</span>}{title}{item.text&&<p>{item.text}</p>}{showPrice&&item.price&&<div className="bhx-service-price">{item.price}</div>}{showRating&&Number(item.rating)>0&&<div className="bhx-service-rating" aria-label={`${Number(item.rating)} out of 5 stars`}><strong>{Number(item.rating).toFixed(1)}</strong><span aria-hidden="true">{'★'.repeat(Math.max(0,Math.min(5,Math.round(Number(item.rating)))))}</span>{item.reviewCount!=null&&<small>({item.reviewCount})</small>}{item.reviewText&&<small>{item.reviewText}</small>}</div>}{Array.isArray(item.features)&&item.features.length>0&&<ul>{item.features.map((f:string,j:number)=><li key={j}>{f}</li>)}</ul>}{item.linkText&&href&&<a className="text-link" href={href} target={item.linkTarget==='new'?'_blank':undefined} rel={item.linkTarget==='new'?'noopener noreferrer':undefined}>{item.linkText} →</a>}{item.showIconButtons===true&&buttons.length>0&&<div className={`bhx-service-icon-buttons bhx-service-icon-buttons-${String(data.servicesIconButtonPlacementV1||'below')}`}>{buttons.map((b:any,j:number)=>{const h=serviceLink(b.linkType,b.link);return h?<a key={b._key||j} href={h} aria-label={clean(b.label||`Action ${j+1}`)} target={b.target==='blank'?'_blank':undefined} rel={b.target==='blank'?'noopener noreferrer':undefined}><V1Icon name={b.icon||'outline-link'} size={20}/>{String(data.servicesIconButtonContentModeV1||'icon')==='icon_text'&&b.label?<span>{b.label}</span>:null}</a>:null})}</div>}</div>}</>
   return <article className={`bhx-service-card ${item.cornerBorderEnabled?'has-corner-border':''}`} key={item._key||i} style={cardStyle}>{content}</article>
 })}</div><SectionActions data={data}/></>
}

function videoEmbed(urlValue:any,startValue:any,titleValue:any){const url=clean(urlValue).trim();if(!/^https?:\/\//i.test(url))return null;const start=Math.max(0,Number(startValue||0));const yt=url.match(/(?:youtube(?:-nocookie)?\.com\/(?:watch\?(?:[^#]*&)?v=|embed\/|shorts\/|live\/)|youtu\.be\/)([A-Za-z0-9_-]{11})/i);if(yt){const src=`https://www.youtube-nocookie.com/embed/${yt[1]}?rel=0&modestbranding=1${start>0?`&start=${Math.floor(start)}`:''}`;return <iframe src={src} title={clean(titleValue||'Video')} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/>}const vm=url.match(/vimeo\.com\/(?:video\/)?([0-9]+)/i);if(vm)return <iframe src={`https://player.vimeo.com/video/${vm[1]}`} title={clean(titleValue||'Video')} loading="lazy" allow="autoplay; fullscreen; picture-in-picture" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/>;if(/\.(?:mp4|webm|ogg|ogv|mov)(?:$|[?#])/i.test(url))return <video src={url} title={clean(titleValue||'Video')} controls playsInline preload="metadata"/>;return <a className="bhx-v1-video-link" href={url} target="_blank" rel="noopener noreferrer">Open video ↗</a>}
function TextMedia({data}:{data:any}){
 const mediaOneType=String(data.textMediaTypeV1||'image');const mediaOneImage=data.textMediaImageV1||data.media;const mediaOneVideo=data.textMediaVideoUrlV1||data.videoUrl
 const mediaTwoType=String(data.textMediaSecondTypeV1||'none');const mediaTwoImage=data.textMediaSecondImageV1;const mediaTwoVideo=data.textMediaSecondVideoUrlV1
 const renderMedia=(type:string,image:any,video:any,start:any,label:string)=>type==='video'?videoEmbed(video,start,label):image?.asset?<Image src={imageUrl(image,1400,1000)} alt={clean(label)} width={1400} height={1000}/>:null
 const one=renderMedia(mediaOneType,mediaOneImage,mediaOneVideo,data.textMediaVideoStartV1,data.heading||'Media One');const two=mediaTwoType==='none'?null:renderMedia(mediaTwoType,mediaTwoImage,mediaTwoVideo,data.textMediaSecondVideoStartV1,`${data.heading||'Media'} — Two`)
 const text=<div className="bhx-v1-column bhx-v1-text"><SectionHeaderV1 data={data}/>{data.textMediaReadMoreEnabledV1===true&&data.textMediaReadMoreTextV1?<TextMediaReadMoreV1 label={String(data.textMediaReadMoreTextV1)} content={data.textMediaReadMoreContentV1?String(data.textMediaReadMoreContentV1):undefined} style={String(data.textMediaReadMoreStyleV1||'inline')}/>:null}<SectionActions data={data}/></div>
 const mediaCol=<div className={`bhx-v1-column bhx-v1-media bhx-media-cols-${Math.max(1,Math.min(2,Number(data.textMediaMediaColumnsDesktopV1||1)))}`}>{one}{two}</div>
 const layout=String(data.textMediaLayoutDesktopV1Exact||data.textMediaLayoutDesktopV1||data.desktopLayout||'text-media'),mobile=String(data.textMediaLayoutMobileV1Exact||data.textMediaLayoutMobileV1||'text-media');const balance=String(data.textMediaSplitRatioDesktopV1||data.textMediaBalanceV1||data.widthBalance||'50/50').replace('/','-')
 return <div className={`bhx-v1-two-column bhx-v1-layout-${layout} bhx-v1-mobile-${mobile} bhx-v1-balance-${balance}`}>{layout==='media-text'?<>{mediaCol}{text}</>:<>{text}{mediaCol}</>}</div>
}

function Code({data}:{data:any}){const allow=process.env.ALLOW_ADVANCED_CODE==='true';return <CodeSectionV1 data={data} allow={allow}/>}

function TextText({data,instanceKey}:{data:any;instanceKey?:string}){return <TextTextV1 data={data} instanceKey={instanceKey}/>}



function Social({data}:{data:any}){const items=Array.isArray(data.socialItemsV1)&&data.socialItemsV1.length?data.socialItemsV1:legacyItems(data).map((x:any)=>({network:x.eyebrow,label:x.title,url:x.link?.url,icon:x.iconText,linkTarget:x.link?.newWindow?'new':'same'}));return <><SectionHeaderV1 data={data}/><div className={`bhx-social-list bhx-social-${String(data.socialLayoutV1||'icons')}`}>{items.map((x:any,i:number)=>{const h=safeHref(x.url);return h?<a key={x._key||i} href={h} target={x.linkTarget==='new'?'_blank':undefined} rel={x.linkTarget==='new'?'noopener noreferrer':undefined}><V1Icon name={x.icon||String(x.network||'').toLowerCase()} size={28}/><span>{x.label||x.network}</span></a>:null})}</div></>}

function TextCards({data}:{data:any}){const items=Array.isArray(data.textCardsItemsV1)&&data.textCardsItemsV1.length?data.textCardsItemsV1:legacyItems(data);return <div className={`bhx-text-cards bhx-v1-balance-${String(data.textCardsBalanceV1||'40/60').replace('/','-')}`}><div className="bhx-text-cards-copy"><SectionHeaderV1 data={data}/></div><div className="bhx-text-cards-grid" style={{'--bhx-text-card-cols':Math.max(1,Math.min(4,Number(data.textCardsColumnsV1||2)))} as any}>{items.map((x:any,i:number)=><article key={x._key||i} className="bhx-text-card">{x.icon&&<V1Icon name={x.icon}/>} {x.image?.asset&&<Image src={imageUrl(x.image,720,480)} alt={clean(x.title)} width={720} height={480}/>} {x.eyebrow&&<span className="eyebrow">{x.eyebrow}</span>}<h3>{x.title}</h3>{x.text&&<p>{x.text}</p>}{x.linkText&&x.url&&<a href={safeHref(x.url)||'#'}>{x.linkText} →</a>}</article>)}</div></div>}

function Lists({data}:{data:any}){const items=Array.isArray(data.listItemsV1)&&data.listItemsV1.length?data.listItemsV1:legacyItems(data).map((x:any,i:number)=>({icon:x.iconText,number:x.value||String(i+1),title:x.title,text:x.text,url:x.link?.url,linkText:x.link?.label}));return <><SectionHeaderV1 data={data}/><div className={`bhx-list-types bhx-list-${String(data.listStyleV1||'icon')}`} style={{'--bhx-list-cols':Math.max(1,Math.min(4,Number(data.listColumnsV1||1)))} as any}>{items.map((x:any,i:number)=><article className="bhx-list-item" key={x._key||i}><div className="bhx-list-marker">{String(data.listStyleV1)==='numbered'?(x.number||i+1):<V1Icon name={String(data.listStyleV1)==='checklist'?'outline-check-circle':x.icon}/>}</div><div><h3>{x.title}</h3>{x.text&&<p>{x.text}</p>}{x.linkText&&x.url&&<a href={safeHref(x.url)||'#'}>{x.linkText} →</a>}</div></article>)}</div></>}

export default function WebSectionStaticV1({data,type,instanceKey}:{data:any;type:string;instanceKey?:string}){
 switch(type){
  case 'services':return <Services data={data}/>
  case 'textmedia':return <TextMedia data={data}/>
  case 'code':return <Code data={data}/>
  case 'texttext':return <TextText data={data} instanceKey={instanceKey}/>
  case 'social_media':return <Social data={data}/>
  case 'text_cards':return <TextCards data={data}/>
  case 'list_types':return <Lists data={data}/>
  default:return <><SectionHeaderV1 data={data}/><SectionActions data={data}/></>
 }
}
